controller_manager:
  ros__parameters:
    update_rate: 30 # Must be an integer

my_robot_system: # This name MUST match the <hardware_interface><name> tag in your xacro file.
  ros__parameters:
    interface_name: MyRobotSystem # This name MUST match the <hardware_interface><name> tag in your xacro file.
    joints:
      - L_hip_joint
      - L_thigh
      - L_knee
      - L_ankle_pitch
      - L_ankle_roll
      - R_hip_joint
      - R_thigh
      - R_knee
      - R_ankle_pitch
      - R_ankle_roll
      - L_shoulder_joint
      - L_upperarm
      - L_forearm
      - R_shoulder_joint
      - R_upperarm
      - R_forearm
      - Head

    # These must match the <command_interface> and <state_interface> tags defined in the xacro file
    command_interfaces:
      - position # Or velocity, depending on your setup
    state_interfaces:
      - position # Or velocity, depending on your setup

    type: joint_trajectory_controller/JointTrajectoryController # Or other controller type
